window.SITE_COPY = {
  en: {
    downloadCV: 'Curriculum vitae ↗', submissionsTitle: 'Selected submissions',
    webprogramStatus: '· Under review · Fourth author',
    webprogramSummary: 'Evaluating whether coding agents can reconstruct executable applications from black-box interaction, with checks spanning interfaces, services, and persistent state.',
    educationTitle: 'Education', phdDegree: 'Ph.D. in Artificial Intelligence (in progress)', mastersDegree: 'Master’s in Data Science', bachelorsDegree: 'Bachelor’s in Electronic Information', nju: 'Nanjing University', whu: 'Wuhan University',

    projectSite: 'Project site ↗', skip: 'Skip to content', navResearch: 'Research', navPapers: 'Publications', navAbout: 'About',
    role: 'Ph.D. candidate', affiliation: 'Nanjing University', location: 'Nanjing, China',
    profileNote: 'Language agents\nMulti-agent systems\nGraph learning',
    eyebrow: 'Research in language agents & learning', heroTitle: 'Language agents,\nfrom coordination\nto execution.',
    heroLead: 'I study how agents coordinate, acquire evidence, and act within real execution environments. My work connects multi-agent dynamics, speculative exploration, and harness-aligned learning.',
    tagAgents: 'Agent systems', tagRuntime: 'Runtime semantics', tagGraphs: 'Learning on graphs',
    researchTitle: 'Current research', underReview: 'Under review',
    perseusSummary: 'Broadening discovery while one Actor retains task authority. Independent speculative acquisitions, persistent Futures, and ready-only evidence let exploration continue alongside the main trajectory.',
    perseusMeta: 'Inference-time exploration · Asynchronous execution',
    hpdSummary: 'Learning policies that respect the harness they run in. Verified action targets and runtime control-document views provide complementary supervision for a single model, preserving the native deployment interface.',
    hpdMeta: 'Policy distillation · Harness-compatible agents', viewDiagram: 'View diagram ↗',
    reviewNote: 'Ongoing manuscripts are shown as research summaries. Under-review work is listed separately from published papers.',
    publicationsTitle: 'Selected publications', peerReviewed: 'Peer-reviewed',
    orchestratorSummary: 'A mean-field entropy model connects task resolution and context loading, explaining instability in centralized language-agent orchestration.',
    kpclSummary: 'Preference-aware contrastive learning and rationale attention filter task-irrelevant knowledge-graph noise for recommendation.',
    logProceedings: '· Proceedings published in PMLR 269, 2025', paper: 'Paper ↗', code: 'Code ↗', bibtex: 'BibTeX',
    aboutTitle: 'About & interests', aboutCopy: 'I am a Ph.D. candidate at Nanjing University. My research examines the relationship between agent policies and their execution environments: how coordination evolves, how useful information arrives, and how runtime constraints can be learned.',
    aboutGraphs: 'My earlier work studies knowledge-aware recommendation through graph representation learning. Across these topics, I am interested in understanding the structure behind effective learning and decision-making systems.',
    focusTitle: 'Research focus', focusOne: 'LLM agents & multi-agent dynamics', focusTwo: 'Speculative & asynchronous execution', focusThree: 'Harness-aligned policy learning', focusFour: 'Knowledge graphs & recommendation',
    updated: 'Updated October 2026', backTop: 'Back to top ↑'
  },
  zh: {
    downloadCV: '学术简历 ↗', submissionsTitle: '代表性投稿',
    webprogramStatus: '· 在审 · 第四作者',
    webprogramSummary: '评估编程智能体能否通过黑盒交互重建可执行应用，验证覆盖界面、服务与持久化状态。',
    educationTitle: '教育经历', phdDegree: '人工智能 · 博士在读', mastersDegree: '数据科学 · 硕士', bachelorsDegree: '电子信息 · 本科', nju: '南京大学', whu: '武汉大学',

    projectSite: '项目主页 ↗', skip: '跳转到正文', navResearch: '研究', navPapers: '发表论文', navAbout: '关于',
    role: '博士候选人', affiliation: '南京大学', location: '中国 · 南京',
    profileNote: '语言智能体\n多智能体系统\n图学习',
    eyebrow: '语言智能体与机器学习研究', heroTitle: '语言智能体，\n从协作机制\n到原生执行。',
    heroLead: '我研究智能体如何协作、获取证据，并在真实执行环境中行动。近期工作连接多智能体动力学、投机探索与 harness 对齐学习。',
    tagAgents: '智能体系统', tagRuntime: '运行时语义', tagGraphs: '图学习',
    researchTitle: '近期研究', underReview: '在审稿件',
    perseusSummary: '在保留唯一 Actor 决策权的同时扩大探索广度。独立投机采集、持续 Future 与只接收已完成结果的证据通道，让探索和主线任务异步推进。',
    perseusMeta: '推理期探索 · 异步执行',
    hpdSummary: '让智能体策略学习其运行环境的约束。经验证的动作目标与运行时控制文档视图共同监督单一模型，同时保留原生部署接口。',
    hpdMeta: '策略蒸馏 · Harness 对齐', viewDiagram: '查看完整图示 ↗',
    reviewNote: '在审工作仅展示研究简介，与正式发表论文分开列出。',
    publicationsTitle: '代表性发表论文', peerReviewed: '同行评审',
    orchestratorSummary: '用平均场熵动力学连接任务解决与上下文累积，解释集中式语言智能体编排中的不稳定性。',
    kpclSummary: '通过偏好感知对比学习与理由注意力，过滤知识图谱中与推荐任务无关的噪声。',
    logProceedings: '· 论文集发表于 PMLR 269，2025 年', paper: '论文 ↗', code: '代码 ↗', bibtex: '引用格式',
    aboutTitle: '关于与研究兴趣', aboutCopy: '我是南京大学博士候选人。我的研究关注智能体策略与执行环境之间的关系：协作如何演化、有用的信息如何到达决策，以及运行时约束如何被模型学习。',
    aboutGraphs: '此前的工作通过图表示学习研究知识感知推荐。贯穿这些方向的问题是：如何理解有效学习与决策系统背后的结构。',
    focusTitle: '研究方向', focusOne: '语言智能体与多智能体动力学', focusTwo: '投机探索与异步执行', focusThree: 'Harness 对齐策略学习', focusFour: '知识图谱与推荐系统',
    updated: '更新于 2026 年 10 月', backTop: '返回顶部 ↑'
  }
};
